cuckoo: version bump. install fix. dep (sflock) needs to be fixed

diff --git a/packages/cuckoo/PKGBUILD b/packages/cuckoo/PKGBUILD
--- a/packages/cuckoo/PKGBUILD
+++ b/packages/cuckoo/PKGBUILD
@@ -28,7 +28,9 @@ depends=('python2' 'python2-sqlalchemy' 'python2-dpkt' 'python2-jinja'
          'python2-itsdangerous' 'python2-mako' 'python2-markupsafe'
          'python2-ndg-httpsclient' 'python2-pyasn1' 'python2-pycparser'
          'python2-pyopenssl' 'python2-dateutil' 'python2-requests' 'python2-six'
-         'python2-werkzeug' 'python2-tlslite-ng' 'python2-wakeonlan')
+         'python2-werkzeug' 'python2-tlslite-ng' 'python2-wakeonlan'
+         'python2-sflock')
+makedepens=('python2-pip')
 source=("https://files.pythonhosted.org/packages/ae/cc/2ee841d414a7274455bb0d969567ba9a4cd72594e3ad34dbdee98f999c7b/Cuckoo-$pkgver.tar.gz"
         'https://raw.githubusercontent.com/BlackArch/tcpdump_net_raw/master/tcpdump_net_raw.c')
 sha512sums=('59cde295d9333bff08108a9340ef2ad84b44db4a56b484bcf622d09831491ed9be8b14b3feec4fc821653b6270ffad9cad4f269ce31b460b2dbcc814cea32391'
@@ -58,24 +60,27 @@ package() {
   mkdir -p "$pkgdir/usr/bin"
   mkdir -p "$pkgdir/opt/${pkgname}"
 
+  PIP_CONFIG_FILE=/dev/null pip2 install --isolated --root="$pkgdir" \
+    --ignore-installed --no-deps ./
+
   install -m754 "$srcdir/tcpdump_net_raw" "$pkgdir/opt/${pkgname}/cuckoo_tcpdump"
 
-  cp --no-preserve=ownership -a * "$pkgdir/opt/${pkgname}"
+#  cp --no-preserve=ownership -a * "$pkgdir/opt/${pkgname}"
 
-  chmod u+rwX,g+rwX,o+rX -R "$pkgdir/opt"
+#  chmod u+rwX,g+rwX,o+rX -R "$pkgdir/opt"
 
-  cat > "$pkgdir/usr/bin/cuckoo" << EOF
+#  cat > "$pkgdir/usr/bin/cuckoo" << EOF
 #!/bin/sh
 
-if ! id | grep -q '(cuckoo)' && ! [ \$EUID -eq 0 ] ; then
-  echo "ERROR: Add yourself to the cuckoo group to use cuckoo as an unprivledged user."
-  exit 1
-fi
+#if ! id | grep -q '(cuckoo)' && ! [ \$EUID -eq 0 ] ; then
+#  echo "ERROR: Add yourself to the cuckoo group to use cuckoo as an unprivledged user."
+#  exit 1
+#fi
 
-cd /opt/cuckoo
-exec python2 cuckoo.py "\${@}"
-EOF
+#cd /opt/cuckoo
+#exec python2 cuckoo.py "\${@}"
+#EOF
 
-  chmod a+x "$pkgdir/usr/bin/cuckoo"
+#  chmod a+x "$pkgdir/usr/bin/cuckoo"
 }
 
