packages: fix installs, deps, etc.

diff --git a/packages/cuckoo/PKGBUILD b/packages/cuckoo/PKGBUILD
--- a/packages/cuckoo/PKGBUILD
+++ b/packages/cuckoo/PKGBUILD
@@ -65,27 +65,27 @@ package() {
   install -dm 755 "$pkgdir/usr/bin"
   install -dm 755 "$pkgdir/opt/$pkgname"
 
-  PIP_CONFIG_FILE=/dev/null pip2 install --isolated --root="$pkgdir" \
-    --ignore-installed --no-deps ./
+  #PIP_CONFIG_FILE=/dev/null pip2 install --isolated --root="$pkgdir" \
+  #  --ignore-installed --no-deps ./
 
   install -m 754 "$srcdir/tcpdump_net_raw" "$pkgdir/opt/$pkgname/cuckoo_tcpdump"
 
-#  cp --no-preserve=ownership -a * "$pkgdir/opt/${pkgname}"
+  cp --no-preserve=ownership -a * "$pkgdir/opt/$pkgname/"
 
-#  chmod u+rwX,g+rwX,o+rX -R "$pkgdir/opt"
+  chmod u+rwX,g+rwX,o+rX -R "$pkgdir/opt"
 
-#  cat > "$pkgdir/usr/bin/cuckoo" << EOF
+  cat > "$pkgdir/usr/bin/$pkgname" << EOF
 #!/bin/sh
 
-#if ! id | grep -q '(cuckoo)' && ! [ \$EUID -eq 0 ] ; then
-#  echo "ERROR: Add yourself to the cuckoo group to use cuckoo as an unprivledged user."
-#  exit 1
-#fi
+if ! id | grep -q '(cuckoo)' && ! [ \$EUID -eq 0 ] ; then
+  echo "ERROR: Add yourself to the cuckoo group to use cuckoo as an unprivledged user."
+  exit 1
+fi
 
-#cd /opt/cuckoo
-#exec python2 cuckoo.py "\${@}"
-#EOF
+cd /opt/cuckoo
+exec python2 cuckoo.py "\$@"
+EOF
 
-#  chmod +x "$pkgdir/usr/bin/cuckoo"
+  chmod +x "$pkgdir/usr/bin/$pkgname"
 }
 
