barelease: Add a safety check.

diff --git a/scripts/barelease b/scripts/barelease
--- a/scripts/barelease
+++ b/scripts/barelease
@@ -298,6 +298,11 @@ do_release() {
 		echo "pulling..."
 		rsync -z -e "ssh -l $user" "$site:$sitedir/blackarch/$repo/os/$arch"/{blackarch.db.tar.gz,blackarch.files.tar.gz} .
 
+		if [[ ! -r blackarch.db.tar.gz ]] ; then
+			err 'sync error. try again.'
+			exit 1
+		fi
+
 		if $remove ; then
 			for package in "${packages[@]}" ; do
 				echo 'removing from database...'
