barelease: Add better help output.

diff --git a/scripts/barelease b/scripts/barelease
--- a/scripts/barelease
+++ b/scripts/barelease
@@ -98,6 +98,15 @@ parse_args() {
 				sitedir=$2
 				shift
 				;;
+			-h)
+				usage
+				exit
+				;;
+			*)
+				err "invalid arg: $1"
+				usage
+				exit 1
+				;;
 		esac
 		shift
 	done
