barelease: Fix an error in remote_lock.

diff --git a/scripts/barelease b/scripts/barelease
--- a/scripts/barelease
+++ b/scripts/barelease
@@ -146,7 +146,7 @@ start_ssh_agent() {
 # This runs on the remote host.
 remote_lock() {
 	if ! mkdir -m000 /tmp/blackarch.lck ; then
-		err 'unable to obtain lock. remove /tmp/blackarch.lck perhaps?'
+		echo >&2 'unable to obtain lock.'
 		exit 1
 	fi
 }
