make-repo: Fix error code handling.

diff --git a/scripts/make-repo b/scripts/make-repo
--- a/scripts/make-repo
+++ b/scripts/make-repo
@@ -26,8 +26,9 @@ while read pkgbuild ; do
 	cd "$builddir/$(basename "$(dirname "$pkgbuild")")"
 
 	makepkg -s --noconfirm --sign 2>&1
-	if [[ $? != 0 ]] ; then
-		echo >&2 "'$pkgbuild' failed with error code $?"
+	ret=$?
+	if [[ $ret != 0 ]] ; then
+		echo >&2 "'$pkgbuild' failed with error code $ret"
 		continue
 	fi
 
