scripts/make-repo: Add even more information.

diff --git a/scripts/make-repo b/scripts/make-repo
--- a/scripts/make-repo
+++ b/scripts/make-repo
@@ -8,9 +8,21 @@ sign=true
 # The sorts are sensitive.
 export LC_ALL=POSIX
 
+msg() {
+	echo >&2 "$*"
+}
+
+msg2() {
+	echo >&2 "----> $*"
+}
+
+warn() {
+	echo >&2 "<-!-> $*"
+}
+
 cache_rights() {
-	echo >&2 'attempting to cache rights...'
-	sudo -v || echo >&2 'sudo failed. continuing build anyways.'
+	msg 'attempting to cache rights...'
+	sudo -v || msg 'sudo failed. continuing build anyways.'
 }
 
 for arg ; do
@@ -19,7 +31,7 @@ for arg ; do
 			sign=false
 			;;
 		*)
-			echo >&2 "'$arg' not recognized."
+			msg "'$arg' not recognized."
 			exit 1
 			;;
 	esac
@@ -33,31 +45,35 @@ cache_rights
 basedir=$(realpath "$(dirname "$0")")
 cd "$basedir/.."
 
+# PKGBUILDs and tracked source come from here.
 pkgdir=$(realpath packages)
-repodir=$(realpath repo)
+
+# PKGBUILDs and tracked source are copied here.
 builddir=$(realpath build)
+mkdir -p "$builddir"
+
+# Built package go here.
+repodir=$(realpath repo)
 mkdir -p "$repodir"
-mkdir -p "$builddir"
-mkdir -p "$builddir"
 
-cd packages
+cd "$pkgdir"
 
-echo >&2 'generating depth list...'
+msg 'generating depth list...'
 "$basedir/depth-list" |
 while read item ; do (
 	cache_rights
 
 	read depth pack <<< "$item"
-	echo >&2 "Depth: $depth"
-	echo >&2 "Name: $pack"
+	msg "Depth: $depth"
+	msg "Name: $pack"
 
-	echo >&2 'copying...'
+	msg2 'copying...'
 
 	# packages/*/<package> -> build/<package>
 	cp -vfr "$pack" "$builddir"
 	cd "$builddir/$pack"
 
-	echo >&2 'cleaning...'
+	msg2 'cleaning...'
 
 	# Better than nothing cleaning.
 	# It is preferable to run 'git clean -dXf packages' or work with a fresh
@@ -65,7 +81,7 @@ while read item ; do (
 	rm -vrf */
 	rm -vf *.{xz,gz,zip,bzip2,gunzip2,tgz,tar}
 
-	echo >&2 'building...'
+	msg2 'building...'
 
 	# Build.
 	makepkg -s --nocheck --noconfirm 2>&1
@@ -73,16 +89,17 @@ while read item ; do (
 	# Log errors.
 	ret=$?
 	if [[ $ret != 0 ]] ; then
-		echo >&2 "<-!-> '$pack' failed with error code $ret"
+		warn "'$pack' failed with error code $ret"
 		continue
 	fi
 
 	# Install if necessary.
 	if [[ $depth != 1 ]] ; then
 		sudo pacman --asdeps --noconfirm -U *.pkg.tar.xz ||
-		  echo "<-!-> '$pack' failed to install"
+		  warn "'$pack' failed to install"
 	fi
 
+	msg2 'moving to repo...'
 	# Move package into the repo.
 	mv *.pkg.tar.xz "$repodir"
 ) done
@@ -91,10 +108,12 @@ while read item ; do (
 cd "$repodir"
 
 if $sign ; then
+	msg 'signing packages...'
 	for pack in *.pkg.tar.xz ; do
 		gpg -b "$pack"
 	done
 fi
-repo-add blackarch.db.tar.gz *.pkg.tar.xz
+msg 'creating database...'
+repo-add blackarch.db.tar.gz *.pkg.tar.xz 2>&1
 
 # vim: set ft=zsh:
