scripts/make-package: Fix the error format.

diff --git a/scripts/make-package b/scripts/make-package
--- a/scripts/make-package
+++ b/scripts/make-package
@@ -12,11 +12,11 @@ msg() {
 }
 
 msg2() {
-	echo >&2 "-----: $*"
+	echo >&2 "-----> $*"
 }
 
 warn() {
-	echo >&2 "error: $*"
+	echo >&2 "%error% $*"
 }
 
 acquire_lock() {
