make-repo: Make output easier to grep through.
This adds `<-!->` markers to output.

diff --git a/scripts/make-repo b/scripts/make-repo
--- a/scripts/make-repo
+++ b/scripts/make-repo
@@ -73,19 +73,19 @@ while read item ; do (
 	# Log errors.
 	ret=$?
 	if [[ $ret != 0 ]] ; then
-		echo >&2 "'$pack' failed with error code $ret"
+		echo >&2 "<-!-> '$pack' failed with error code $ret"
 		continue
 	fi
 
 	# Move the signatures.
 	# These may interfere with package installation.
 	mv *.pkg.tar.xz.sig "$repodir/signatures" ||
-	  echo >&2 "'$pack' signing failed"
+	  echo >&2 "<-!-> '$pack' signing failed"
 
 	# Install if necessary.
 	if [[ $depth != 1 ]] ; then
 		sudo pacman --asdeps --noconfirm -U *.pkg.tar.xz ||
-		  echo "'$pack' failed to install"
+		  echo "<-!-> '$pack' failed to install"
 	fi
 
 	# Move package into the repo.
