scripts/make-repo: Make the error output more uniform.

diff --git a/scripts/make-repo b/scripts/make-repo
--- a/scripts/make-repo
+++ b/scripts/make-repo
@@ -13,11 +13,11 @@ msg() {
 }
 
 msg2() {
-	echo >&2 "----> $*"
+	echo >&2 "-----> $*"
 }
 
 warn() {
-	echo >&2 "<-!-> $*"
+	echo >&2 "error> $*"
 }
 
 cache_rights() {
@@ -64,8 +64,8 @@ while read item ; do (
 	cache_rights
 
 	read depth pack <<< "$item"
-	msg "Depth: $depth"
-	msg "Name: $pack"
+	msg "depth> $depth"
+	msg "-name> $pack"
 
 	msg2 'copying...'
 
@@ -93,7 +93,7 @@ while read item ; do (
 		continue
 	fi
 
-	# Install if necessary.
+	# Install if dependency.
 	if [[ $depth != 1 ]] ; then
 		sudo pacman --asdeps --noconfirm -U *.pkg.tar.xz ||
 		  warn "'$pack' failed to install"
