scripts/outdated: Die if we could not get the database.

diff --git a/scripts/outdated b/scripts/outdated
--- a/scripts/outdated
+++ b/scripts/outdated
@@ -67,8 +67,11 @@ get_db() {
 	local arch=$1
 
 	err 'getting database...'
-	curl -s "$site/$arch/blackarch.db.tar.gz" |
-	  tar xz -C "$db"
+	if ! curl -s "$site/$arch/blackarch.db.tar.gz" |
+	     tar xz -C "$db" ; then
+		 err 'failed to get database.'
+		 exit 1
+	fi
 }
 
 clean_db() {
