prep: Improve some things.

diff --git a/scripts/prep b/scripts/prep
--- a/scripts/prep
+++ b/scripts/prep
@@ -21,18 +21,20 @@ if (( $# < 1 )) ; then
 	cat > "$pkgbuild_tmp"
 	output=/dev/stdout
 else
+	if [[ ! -r "$1" ]] ; then
+		err "could not read '$1'."
+		exit 1
+	fi
+
 	err "cleaning '$1'..."
+
 	cat "$1" > "$pkgbuild_tmp"
 	output=$1
 fi
 
 source "$pkgbuild_tmp"
-namcap "$pkgbuild_tmp"
-
-if [[ ! -r "$pkgbuild_tmp" ]] ; then
-	err "could not read '$pkgbuild_tmp'."
-	exit 1
-fi
+# TODO: Fix this.
+#namcap "$pkgbuild_tmp"
 
 # Expand tabs to two spaces
 err "expanding tabs..."
