scripts/prep: Comment out the license checking.
It's too annoying.

diff --git a/scripts/prep b/scripts/prep
--- a/scripts/prep
+++ b/scripts/prep
@@ -29,19 +29,16 @@ echo "removing vim modeline..."
 sed -i '/#\s*vim:/d' "$pkgbuild"
 
 # Check license
-echo "checking license..."
-(
-source "$pkgbuild"
-for lic in "${license[@]}" ; do
-	if [[ ! "$lic" =~ \
-		   ^([Uu]nknown|[Cc]ustom:.*|BSD|MIT|ZLIB|[Pp]ython)$ ]] ; then
-		[[ -z "$lic" ]] && echo >&2 "'$pkgbuild' has no license."
-		[[ -e /usr/share/licenses/common/$lic ]] ||
-		echo >&2 "'$pkgbuild' has invalid license: '$lic'"
-		sed -i '1i\# TODO: check license' "$pkgbuild"
-	fi
-done
-)
+#echo "checking license..."
+#for lic in "${license[@]}" ; do
+#	if [[ ! "$lic" =~ \
+#		   ^([Uu]nknown|[Cc]ustom.*|BSD|MIT|ZLIB|[Pp]ython)$ ]] ; then
+#		[[ -z "$lic" ]] && echo >&2 "'$pkgbuild' has no license."
+#		[[ -e /usr/share/licenses/common/$lic ]] ||
+#		echo >&2 "'$pkgbuild' has invalid license: '$lic'"
+#		sed -i '1i\# TODO: check license' "$pkgbuild"
+#	fi
+#done
 
 # Remove Id comment
 echo "removing id comment..."
